### ISSUE TITLE
test_get_image_data_and_filename test is not mocked

### ISSUE THREAD

**Issue by jhubert** [jhubert/pydocx-s3-images#2]
The test reaches out to httpbin to get the image instead of just mocking up the response.

**Comment by botzill** [comment]
Fixed 47dc7ad3b00bfa23c31a9e49a9cbdf3a6ba95fb6.

**Comment by jhubert** [comment]
This doesn't seem to be fixed. I disabled my internet and the tests still freeze for me :question:

**Comment by botzill** [comment]
Fixed 6a507aa6ac9196903bf63d650f77f2d655b80b90.

**Comment by jhubert** [comment]
verified. :rocket:
